### ISSUE TITLE
Decide on angular binning for angle range injection

### ISSUE THREAD

**Issue by jlazar17** [icecube/TauRunner#35]

**Comment by apizzuto** [comment]
Is this referring to how it gets really slow to simulate a range of angles because the code spends most of the time doing the column depth calculation for each track?
If so, I came here to make the same issue, but if these are unrelated I can make a new issue

**Comment by jlazar17** [comment]
Calculate this once for equally spaced costhetas and then interpolate on them in order to compute the granularity and such.

**Comment by apizzuto** [comment]
Done with https://github.com/icecube/TauRunner/pull/50
