### ISSUE TITLE
Energy argument units in README.md

### ISSUE THREAD

**Issue by tbertolez** [icecube/TauRunner#57]
Congratulations on the code! It is working perfectly and smoothly, and helping me a lot :) 

Very small issue: if I am not wrong, the README energy units are not updated with the latest code. In particular, it confuses GeV with eV. 
See for example lines 31-35 in README.md: it says that `-e 1e9` is equivalent to 1EeV, and that the argument units are in GeV. According to what I've seen of the code, I believe it should say that `-e 1e18` is 1EeV, and the argument units are in eV. 
The results obtained by running line 33 in the CLI actually make sense with the energy being in eV: `-e 1e9` (eV) neutrinos don't interact with the Earth.

This same problem is repeated in the following examples.

Again, this is a very small issue! But is easy to correct and may help newcomers like me to get a bit less confused :) Thanks again!

**Comment by jlazar17** [comment]
@tbertolez You are correct; thank you for pointing this out. I have corrected the unit mistake in the README.
