### ISSUE TITLE
Remove nuSQUIDS dependency

### ISSUE THREAD

**Issue by apizzuto** [icecube/TauRunner#9]
This is already underway. Includes tabling the cross sections and implementing units locally

**Comment by ivan-esteban-phys** [comment]
The python module of the latest nusquids version is no longer named nuSQUIDSpy, but just nuSQuIDS. This is probably irrelevant because you plan to remove this dependency, but I considered it worth mentioning as the current version of TauRunner doesn't work with the latest nusquids. ;-)

**Comment by apizzuto** [comment]
This dependency was removed by Jeff / Ibrahim a few weeks ago. Closing this now
